### PR TITLE
blacken repo

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR `black`ens the code format for `access`. This does note involve any changes in the code base.

xref #21

### CODE REVIEW

**Review by martinfleis — APPROVED** [review]
No idea how to review this but if it is just black then there should be no issue.

**Comment by jGaboardi** [comment]
Yep, only formatting. No change to  functionality at all.

**Review by JamesSaxon — APPROVED** [review]
Likewise to @martinfleis, can't really review.  But if it's just black, then yes please and thank you @jGaboardi.

**Comment by JamesSaxon** [comment]
I'll leaving the squashing honors to you, @jGaboardi

**Pull request merged**
