### PR TITLE
Update default branch name in docs.

### LINKED ISSUE #40: Example notebooks and sources are not available
Most of the links on https://pysal.org/access/tutorials.html are returning 404 : Not Found errors..

### PR DESCRIPTION
**Pull request by sjsrey**
Fixes #40

### CODE REVIEW

**Review by JamesSaxon — APPROVED** [review]
Thanks for doing this.

**Comment by JamesSaxon** [comment]
Uh-oh -- it looks like the example dataset files from `uchicago-csds-access` got stale.

@jkoschinsky, any idea what happened to this bucket or where you could store these in the future?

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
Failures inconsequential to this PR.

**Comment by jkoschinsky** [comment]
Thanks to Jacob Pfingsten for this!

I am a Masters Student in Geoinformatics from Hamburg, Germany and i am currently writing my thesis. My broad topic is the influence of demographic change in germanys on the accessibility of doctors in the metropolitan region of Hamburg. In Germany, more people retire than young people come into the system → supply decreases while demand increases.

For the calculation of TravelTimes i used “r5py” and for the accessibility assessment i am using your very helpful (!) Python module “Access”.

In Germany,  global PPR values are different from those in the US, and they also vary based on the type of physician that one wants to evaluate the accessibility to. 

When i tried to alter these values, i found that nothing was happening at all.

But then i noticed, that the rho-parameter is not passed into the raam.raam-method! To fix that i had to modify the code a little to alter the PPR ("half_life" is mossing too).

Before, it simply ignored the users input into Access.raam() where the function is called:

image
 
It took me a while to understand that i was not misunderstanding the calculation, but instead my input was simply ignored.

So if a future update is planned other users would likely thank you for this tiny adjustment! :)

**Pull request merged**
