### PR TITLE
update infrastructure

### PR DESCRIPTION
**Pull request by knaaptime**
this PR brings access closer in line with the infrastructure used in the rest of the pysal ecosystem. Recently we've migrated to github actions for unit tests and docs hosting (i.e. away from travis and RTD) so this includes recipes to bootstrap that process. Specifically:

- added environment.yml for setting up a conda-based dev environment
- adds .github directory with recipes
  - release_package that creates github and pypi released when a new tag is pushed upstream (resolves discussion in #14 ). To complete this, you'll need to create a token on pypi and save it as a github secret. Me and @jgaboardi can help 
  - unit_tests for running tests in github actions instead of travis. We've also migrated to pytest from nose, so if we adopt this convention we can also drop the .travis.yml and update the yaml files in `.ci` to include pytest instead of nose
  - build_docs for building docs when new commits are added and hosting them on github pages. To complete this, we'd need to go into settings and turn on Github pages to serve from the root of the `gh-pages` branch
- add `requests` to reqs

### CODE REVIEW

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
> Me and @jGaboardi can help

I am very +1 on this. @JamesSaxon you can always tag me for reviews, etc. Happy to assist in any capacity.

**Comment by knaaptime** [comment]
also, if you want to share maintainer access with some of the other core devs like me @jgaboardi and @martinfleis we can take care of the rest of the admin/infrastructure work mentioned in the PR comment to wrap this up and ensure `access` stays conformant with the rest of the ecosystem

**Comment by knaaptime** [comment]
ok, this is good to be merged. With a couple tweaks to the repo settings, tests and docs will run/build in the cloud. As with the other subpackages, new releases can be cut and published by pushing a new tag (push directly upstream, not to your personal fork)

Note that the test suite is more robust now that it's running on GHA instead of travis, as we're testing on all three platforms instead of just linux. Beefing up those tests seems to have [exposed](https://github.com/knaaptime/access/runs/4973807559?check_suite_focus=true) an error downloading one of the geojson files on windows. I'm not sure whats going on there, but it's unrelated to this infrastructure change, so it may have been happening all this time without us noticing. 

Nose isnt used anymore, so #20 can be closed

**Review by jGaboardi — APPROVED** [review]
LGTM. After this gets merged we can make some further enhancements, but no need to do now. Thanks for taking care of this @knaaptime.

**Comment by JamesSaxon** [comment]
Hi Guys -- maintainers seems to be the "access" team, which I didn't create, and don't seem to be able to add members to.  @sjsrey and @martinfleis are also on that list.  Perhaps they can add you.  In the meantime, I just added you both as maintainers directly.  LMK if there's anything else to do on this side.

**Comment by martinfleis** [comment]
I am wondering how I got there :D. But only @sjsrey has rights to add more people.

**Comment by ljwolf** [comment]
I've added eli

**Comment by ljwolf** [comment]
Let me know who else needs adding, @JamesSaxon

**Comment by JamesSaxon** [comment]
Thanks @ljwolf, I think Eli just asked for @jGaboardi

**Comment by knaaptime** [comment]
thanks guys!

**Comment by JamesSaxon** [comment]
Hey @knaaptime, yes I agree to close #20 (which was the DOA version of this one).

I think we may still want a few link updates, e.g., here:

http://pysal.org/model/

Is there an easy way to get redirects from the old site?  From what I can tell, it would entail either one last successful build on RTD or transferring the page to a simple redirect repo.

https://stackoverflow.com/questions/40501719/how-to-redirect-readthedocs-web-pages-to-other-website

Thoughts?

Jamie

**Comment by knaaptime** [comment]
ah, good catch. I woulda forgotten about that link. We can get it sorted on the pysal site pretty quickly (maybe @ecv19 could help?)

**Comment by ecv19** [comment]
pr should be up

**Pull request merged**
