### PR TITLE
Update versioneer, etc

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR updates the versioning implementation using `versioner` (xref #21), along with minor updates to doc links in `README.md`. Also, the `.pre-commit-config.yml` is added, which must be set up locally by devs individually.

### CODE REVIEW

**Comment by jGaboardi** [comment]
@JamesSaxon @martinfleis 

I propose to update [`build_docs.yml`](https://github.com/pysal/access/blob/master/.github/workflows/build_docs.yml) so that it only builds when a fresh version tag is being pushed up. Thoughts? Shall I include it in this PR?

**Comment by martinfleis** [comment]
> Shall I include it in this PR?

I'd leave it for another one.

**Comment by jGaboardi** [comment]
> > Shall I include it in this PR?
> 
> I'd leave it for another one.

👍 This PR is ready for review then.

**Review by martinfleis — APPROVED** [review]
Looks good!

**Comment by jGaboardi** [comment]
@JamesSaxon I'm going to and merging this. We can adjust/remove stuff later if it doesn't suit you (`README` badges, etc.).

**Comment by JamesSaxon** [comment]
Thanks @jGaboardi, I appreciate all your work.

I'm happy to follow standards of the org for the infrastructure stuff & formatting.

**Pull request merged**
